"""Create user data

Revision ID: 94a0e4027788
Revises: 97a365061567
Create Date: 2024-09-01 04:24:59.521076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import select

from src.core.models import User

# revision identifiers, used by Alembic.
revision: str = '94a0e4027788'
down_revision: Union[str, None] = '97a365061567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Get the number of existing users
    existing_user_count = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM users")).scalar()
    count = 10_000_000
    batch_size = 1_000

    # If there are less than 10 million users, insert new users in batches
    if existing_user_count < count:
        for i in range(0, count - existing_user_count, batch_size):
            # Define the new users to insert
            new_users = [
                User().__dict__
                for j in range(batch_size)
            ]

            # Insert the new users
            op.bulk_insert(User.__table__, new_users)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
